# Generated by Django 4.2.2 on 2023-06-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jurisprudencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_jurisprudencias', models.IntegerField()),
                ('tipoCausa', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ('caratula', models.CharField(max_length=255)),
                ('nombreProyecto', models.CharField(max_length=255)),
                ('fechaSentencia', models.DateField()),
                ('descriptores', models.TextField()),
                ('linkSentencia', models.CharField(max_length=255)),
                ('urlSentencia', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('tribunal', models.CharField(max_length=255)),
                ('valores', models.TextField()),
                ('tipo', models.CharField(max_length=255)),
                ('relacionada', models.CharField(max_length=255)),
                ('visitas', models.IntegerField()),
            ],
        ),
    ]
